const state={page:'overview',opps:[],sources:[],meta:{},settings:{},selected:null,modal:null};
const stages=['Signal','Lead','Expected','Pre-market','Live Tender','Pitch','Submitted','Won','Lost'];
const $=s=>document.querySelector(s);
const store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function fmtMoney(o){if(!o.budget_min&&!o.budget_max)return '—';let f=n=>new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n);return `${o.currency||'EUR'} ${f(o.budget_min||0)}–${f(o.budget_max||0)}`}
function sc(s){return s>=80?'good':'mid'}
function localPrefs(){return store.get('radarPrefs',{})}
function mergedOpps(){const prefs=localPrefs();const manual=store.get('radarManual',[]);return [...state.opps,...manual].map(o=>({...o,...(prefs[o.id]||{})})).sort((a,b)=>(b.score||0)-(a.score||0))}
function stats(){const o=mergedOpps().filter(x=>!x.rejected);return {act_now:o.filter(x=>x.score>=85||x.stage==='Live Tender').length,live:o.filter(x=>x.stage==='Live Tender').length,expected:o.filter(x=>['Expected','Pre-market'].includes(x.stage)).length,signals:o.filter(x=>['Signal','Lead'].includes(x.stage)).length}}
async function load(){const [opps,sources,meta]=await Promise.all([fetch('./data/opportunities.json').then(r=>r.json()),fetch('./data/sources.json').then(r=>r.json()),fetch('./data/meta.json').then(r=>r.json())]);state.opps=opps;state.sources=sources;state.meta=meta;state.settings=store.get('radarSettings',{company_name:'YIPP',capability_profile:'Interactive museum experiences, physical-digital installations, projection, realtime 3D, sensors, playful learning.',weight_fit:25,weight_budget:10,weight_geo:10,weight_timing:15,weight_confidence:15,weight_strategy:25});render()}
function nav(){return `<div class="sidebar"><div class="brand"><span class="brandmark"></span>Radar</div><div class="nav">${[['overview','Overview'],['opportunities','Opportunities'],['future','Future Radar'],['pitch','Pitch Opportunities'],['organizations','Organizations'],['sources','Sources'],['scout','Scout'],['activity','Intelligence'],['settings','Settings']].map(([id,n])=>`<button class="${state.page===id?'active':''}" data-nav="${id}" aria-label="${n}" aria-current="${state.page===id?'page':'false'}">${n}</button>`).join('')}</div><div class="sidefoot">GitHub Pages edition<br><span class="status">● ${escapeHtml(state.meta.status||'Static')}</span></div></div>`}
function header(title,sub,action=true){return `<div class="topbar"><div><div class="eyebrow">Museum business intelligence</div><div class="title">${title}</div><div class="sub">${sub}</div></div>${action?`<div class="actions"><button class="btn secondaryAction" id="importBtn" aria-label="Import local Museum Radar data">Import</button><button class="btn secondaryAction" id="exportBtn" aria-label="Export local Museum Radar data">Export</button><button class="btn primary" id="newOpp" aria-label="Add opportunity">+ Opportunity</button></div>`:''}</div>`}
function table(opps){if(!opps.length)return `<div class="card empty">No opportunities match these filters.</div>`;return `<div class="card tablewrap"><table class="oppTable"><thead><tr><th>Score</th><th>Opportunity</th><th>Stage</th><th>Location</th><th>Value</th><th>Timing</th></tr></thead><tbody>${opps.map(o=>`<tr data-open="${escapeHtml(o.id)}"><td><span class="score ${sc(o.score)}">${o.score}</span></td><td><div class="name">${escapeHtml(o.title)}</div><div class="muted">${escapeHtml(o.organization)}</div></td><td><span class="badge ${escapeHtml(o.stage)}">${escapeHtml(o.stage)}</span></td><td>${escapeHtml([o.city,o.country].filter(Boolean).join(', ')||'—')}</td><td>${fmtMoney(o)}</td><td>${escapeHtml(o.deadline||o.procurement_window||'—')}</td></tr>`).join('')}</tbody></table></div>`}
function card(o){return `<div class="card oppcard" data-open="${escapeHtml(o.id)}"><div class="top"><span class="badge ${escapeHtml(o.stage)}">${escapeHtml(o.stage)}</span><span class="score ${sc(o.score)}">${o.score}</span></div><h3>${escapeHtml(o.title)}</h3><div class="muted">${escapeHtml(o.organization)} · ${escapeHtml(o.country||'')}</div><p>${escapeHtml(o.summary||'')}</p><div class="meta"><span class="badge">Confidence ${o.confidence||0}%</span><span class="badge">${escapeHtml(o.procurement_window||o.deadline||'Timing unknown')}</span></div></div>`}
function overview(){const s=stats(),o=mergedOpps().filter(x=>!x.rejected);return `${header('Opportunity Radar','Live opportunities, early signals and future museum work in one place.')}<div class="notice">GitHub Pages has no server. Shared discoveries are refreshed by GitHub Actions; Watch/Reject/notes and manual leads are stored in this browser.</div><div class="grid4">${[['Act now',s.act_now],['Live opportunities',s.live],['Expected tenders',s.expected],['Early signals',s.signals]].map(x=>`<div class="metric"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')}</div><div class="section"><div class="sectionhead"><h2>Highest-priority opportunities</h2><span class="muted">Updated ${escapeHtml(state.meta.generated_at||'')}</span></div>${table(o.slice(0,6))}</div><div class="section"><div class="sectionhead"><h2>Future radar</h2></div><div class="cards">${o.filter(x=>['Signal','Lead','Expected','Pre-market'].includes(x.stage)).slice(0,3).map(card).join('')}</div></div>`}
function opportunities(){return `${header('Opportunities','Search, filter and rank the full opportunity pipeline.')}<div class="filters" role="search"><input id="q" aria-label="Search opportunities" placeholder="Search opportunities…"><select id="stageFilter" aria-label="Filter by stage"><option value="">All stages</option>${stages.map(s=>`<option>${s}</option>`).join('')}</select><select id="scoreFilter" aria-label="Filter by minimum score"><option value="0">Any score</option><option value="60">60+</option><option value="75">75+</option><option value="85">85+</option></select><label class="row muted watchToggle"><input type="checkbox" id="watchFilter"> Watched only</label></div><div id="oppResults">${table(mergedOpps().filter(o=>!o.rejected))}</div>`}
function future(){return `${header('Future Radar','Projects likely to produce an interactive tender or pitch before formal procurement.')}<div class="cards">${mergedOpps().filter(x=>['Signal','Lead','Expected','Pre-market'].includes(x.stage)&&!x.rejected).map(card).join('')}</div>`}
function pitches(){return `${header('Pitch Opportunities','Organizations worth approaching before procurement exists.')}<div class="cards">${mergedOpps().filter(x=>x.stage==='Pitch'&&!x.rejected).map(card).join('')}</div>`}
function organizations(){const m=new Map();mergedOpps().forEach(o=>{if(!m.has(o.organization))m.set(o.organization,{name:o.organization,country:o.country,city:o.city,count:0,best:0});let x=m.get(o.organization);x.count++;x.best=Math.max(x.best,o.score||0)});return `${header('Organizations','Clients and institutions connected to discovered opportunities.')}<div class="cards">${[...m.values()].map(o=>`<div class="card source"><div class="kicker">Museum / cultural institution</div><h3>${escapeHtml(o.name)}</h3><div class="muted">${escapeHtml([o.city,o.country].filter(Boolean).join(', '))}</div><p>${o.count} opportunity${o.count===1?'':'ies'} · best score ${o.best}</p></div>`).join('')}</div>`}
function sources(){return `${header('Sources','Automated public-source coverage used by the scheduled Scout.')}<div class="cards">${state.sources.map(s=>`<div class="card source"><div class="row space"><span class="badge">${escapeHtml(s.type)}</span><span class="status">${escapeHtml(s.status)}</span></div><h3>${escapeHtml(s.name)}</h3><div class="muted">${escapeHtml(s.region)}</div><p>${escapeHtml(s.notes||'')}</p>${s.url?`<a class="muted" href="${escapeHtml(s.url)}" target="_blank">Open source ↗</a>`:''}</div>`).join('')}</div>`}
function scout(){return `${header('Scout','Scheduled discovery runs in GitHub Actions and republishes this site.',false)}<div class="grid4"><div class="metric"><b>${state.meta.last_scan_found||0}</b><span>Found last scan</span></div><div class="metric"><b>${state.meta.last_scan_relevant||0}</b><span>Relevant matches</span></div><div class="metric"><b>${state.meta.total_opportunities||mergedOpps().length}</b><span>Total opportunities</span></div><div class="metric"><b>${state.sources.filter(s=>s.status==='Active').length}</b><span>Active sources</span></div></div><div class="card detail settings" style="margin-top:18px"><h2>How automation works</h2><p class="muted">The included GitHub workflow runs on a schedule and on manual dispatch. It executes the Scout script, fetches configured public procurement/news feeds, scores and deduplicates matches, writes updated JSON, then deploys Pages.</p><div class="notice">Last generated: ${escapeHtml(state.meta.generated_at||'not yet')}<br>Last scan: ${escapeHtml(state.meta.last_scan_at||'not yet')}<br>${escapeHtml(state.meta.last_error||'No recorded scanner error.')}</div></div>`}
function activity(){return `${header('Intelligence Activity','Recent evidence and opportunity changes.')}<div class="card">${mergedOpps().slice().sort((a,b)=>(b.updated_at||'').localeCompare(a.updated_at||'')).map(o=>`<div class="source" data-open="${escapeHtml(o.id)}" style="border-bottom:1px solid var(--line);cursor:pointer"><div class="row space"><b>${escapeHtml(o.title)}</b><span class="muted">${escapeHtml((o.updated_at||'').slice(0,10))}</span></div><div class="muted">${escapeHtml(o.stage)} · score ${o.score} · ${(o.evidence||[]).length} evidence items</div></div>`).join('')}</div>`}
function settings(){const s=state.settings;return `${header('Scoring Settings','Local scoring preferences for this browser.',false)}<div class="card detail settings"><div class="formgrid"><div class="field"><label>Company name</label><input id="company_name" value="${escapeHtml(s.company_name)}"></div><div class="field full"><label>Capability profile</label><textarea id="capability_profile">${escapeHtml(s.capability_profile)}</textarea></div>${[['weight_fit','Capability fit'],['weight_budget','Budget'],['weight_geo','Geography'],['weight_timing','Timing'],['weight_confidence','Evidence confidence'],['weight_strategy','Strategic value']].map(([k,n])=>`<div class="field"><label>${n} weight</label><input type="number" id="${k}" value="${s[k]}"></div>`).join('')}<div class="field full"><button class="btn primary" id="saveSettings">Save locally</button></div></div></div>`}
function render(){const fn={overview,opportunities,future,pitch:pitches,organizations,sources,scout,activity,settings}[state.page];$('#app').innerHTML=`<div class="layout">${nav()}<main class="main">${fn()}</main></div>`;bind()}
function getOpp(id){return mergedOpps().find(o=>String(o.id)===String(id))}
function openDetail(id){state.selected=getOpp(id);state.modal='detail';renderModal()}
function renderModal(){document.querySelectorAll('.modalback').forEach(x=>x.remove());if(!state.modal)return;const wrap=document.createElement('div');wrap.className='modalback';if(state.modal==='detail'){const o=state.selected;wrap.innerHTML=`<div class="modal"><div class="row space"><span class="badge ${escapeHtml(o.stage)}">${escapeHtml(o.stage)}</span><button class="btn" data-close>×</button></div><div class="detailgrid"><div class="detail"><div class="kicker">${escapeHtml(o.organization)} · ${escapeHtml(o.country||'')}</div><h1>${escapeHtml(o.title)}</h1><p class="sub">${escapeHtml(o.summary||'')}</p><h3>Why it fits</h3><p>${escapeHtml(o.fit_rationale||'No fit rationale yet.')}</p><h3>Pitch / approach</h3><p>${escapeHtml(o.pitch_angle||'No pitch angle yet.')}</p><h3>Evidence</h3>${(o.evidence||[]).map(e=>`<div class="evidence"><div class="evidenceItem"><b>${escapeHtml(e.title)}</b><small>${escapeHtml(e.date||'')} · ${escapeHtml(e.kind||'Evidence')} · strength ${e.strength||0}%</small><div>${escapeHtml(e.detail||'')}</div>${e.source_url?`<a class="muted" href="${escapeHtml(e.source_url)}" target="_blank">Open evidence source ↗</a>`:''}</div></div>`).join('')||'<div class="notice">No evidence recorded yet.</div>'}</div><div class="detail"><div class="bigscore ${sc(o.score)}">${o.score}</div><div class="muted">Opportunity score</div><h3>Confidence</h3><div>${o.confidence||0}%</div><h3>Estimated value</h3><div>${fmtMoney(o)}</div><h3>Timing</h3><div>${escapeHtml(o.deadline||o.procurement_window||'Unknown')}</div><h3>Next action</h3><div>${escapeHtml(o.next_action||'—')}</div><div style="height:18px"></div><button class="btn" id="watch">${o.watched?'★ Watched':'☆ Watch'}</button> <button class="btn" id="reject">${o.rejected?'Restore':'Reject'}</button></div></div></div>`}
else if(state.modal==='new'){wrap.innerHTML=`<div class="modal"><div class="row space"><h2>Add local opportunity</h2><button class="btn" data-close>×</button></div><div class="formgrid"><div class="field full"><label>Title</label><input id="n_title"></div><div class="field"><label>Organization</label><input id="n_org"></div><div class="field"><label>Country</label><input id="n_country"></div><div class="field"><label>Stage</label><select id="n_stage">${stages.map(s=>`<option>${s}</option>`).join('')}</select></div><div class="field"><label>Score</label><input id="n_score" type="number" value="60"></div><div class="field full"><label>Summary</label><textarea id="n_summary"></textarea></div><div class="field full"><button class="btn primary" id="createOpp">Create locally</button></div></div></div>`}
document.body.appendChild(wrap);wrap.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>wrap.remove());wrap.onclick=e=>{if(e.target===wrap)wrap.remove()};if($('#watch'))$('#watch').onclick=()=>{const p=localPrefs(),id=state.selected.id;p[id]={...(p[id]||{}),watched:!state.selected.watched};store.set('radarPrefs',p);wrap.remove();render()};if($('#reject'))$('#reject').onclick=()=>{const p=localPrefs(),id=state.selected.id;p[id]={...(p[id]||{}),rejected:!state.selected.rejected};store.set('radarPrefs',p);wrap.remove();render()};if($('#createOpp'))$('#createOpp').onclick=()=>{const m=store.get('radarManual',[]);m.push({id:'local-'+Date.now(),title:$('#n_title').value||'Untitled opportunity',organization:$('#n_org').value||'Unknown',country:$('#n_country').value,stage:$('#n_stage').value,score:+$('#n_score').value||60,confidence:50,summary:$('#n_summary').value,sample:false,updated_at:new Date().toISOString(),evidence:[]});store.set('radarManual',m);wrap.remove();render()}}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{state.page=b.dataset.nav;render()});document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>openDetail(x.dataset.open));if($('#newOpp'))$('#newOpp').onclick=()=>{state.modal='new';renderModal()};if(state.page==='opportunities'){['q','stageFilter','scoreFilter','watchFilter'].forEach(id=>$('#'+id).oninput=filterOpps)}if($('#saveSettings'))$('#saveSettings').onclick=()=>{['company_name','capability_profile','weight_fit','weight_budget','weight_geo','weight_timing','weight_confidence','weight_strategy'].forEach(k=>state.settings[k]=$('#'+k).value);store.set('radarSettings',state.settings);alert('Saved locally.')};if($('#exportBtn'))$('#exportBtn').onclick=exportData;if($('#importBtn'))$('#importBtn').onclick=importData}
function filterOpps(){const q=$('#q').value.toLowerCase(),st=$('#stageFilter').value,min=+$('#scoreFilter').value,w=$('#watchFilter').checked;const o=mergedOpps().filter(x=>!x.rejected&&(!q||[x.title,x.organization,x.country,x.city,x.summary].join(' ').toLowerCase().includes(q))&&(!st||x.stage===st)&&x.score>=min&&(!w||x.watched));$('#oppResults').innerHTML=table(o);document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>openDetail(x.dataset.open))}
function exportData(){const blob=new Blob([JSON.stringify({prefs:localPrefs(),manual:store.get('radarManual',[]),settings:state.settings},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='museum-radar-local-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(){const i=document.createElement('input');i.type='file';i.accept='application/json';i.onchange=()=>{const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d.prefs)store.set('radarPrefs',d.prefs);if(d.manual)store.set('radarManual',d.manual);if(d.settings)store.set('radarSettings',d.settings);location.reload()}catch(e){alert('Invalid backup file')}};r.readAsText(i.files[0])};i.click()}
load().catch(e=>{$('#app').innerHTML=`<div class="empty">Could not load Radar: ${escapeHtml(e.message)}</div>`});
